name: common_utilities
description: "Common Utilities for Flutter Developers is a package that offers a versatile collection of essential tools to streamline your Flutter development. It includes utilities for state management, form validation, UI enhancements, and more. Designed with reusability in mind, this package helps you write clean, maintainable code and speeds up your development process. Perfect for both beginners and seasoned developers, these utilities simplify common tasks and enhance your Flutter apps."
version: 0.1.6
homepage: https://github.com/PavanSN/common_utilities.git

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_cubit: ^1.1.0
  lottie: ^3.1.2
  open_settings_plus: ^0.3.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
